### ISSUE TITLE
MYSQL 8 

### ISSUE THREAD

**Issue by jnandal** [guidesmiths/marv-mysql-driver#5]
Issue with SQL 8 
Client does not support authentication protocol requested by server; consider upgrading MySQL client

I got it to work by adding 

`command: --default-authentication-plugin=mysql_native_password`

to my docker compose file.

**Comment by cressie176** [comment]
Hi @jnandal,

Unfortunately this is because of a [long standing issue](https://github.com/mysqljs/mysql/issues/1507) with the underlying mysql client. The best we can do is update the marv-mysql-driver readme and possibly create a marv-mysql2-driver based on https://github.com/sidorares/node-mysql2.

I'll keep this issue open until we update the README.

**Comment by jnandal** [comment]
Would it be possible to create the second driver to use mysql2?  I'm already using mysql2 in my project.

**Comment by cressie176** [comment]
> Would it be possible to create the second driver to use mysql2? I'm already using mysql2 in my project.

Yes, but no guarantees about timescale. I'd also like to investigate if its possible to have a single marv-mysql-driver but being able to select the underlying client.

Out of interest what happens if you add mysql2 to the [driver configuration](https://github.com/guidesmiths/marv-mysql-driver/blob/master/index.js#L24
)?

mysql and mysql2 are supposed to be compatible, so it might just work. It would mean having an unnecessary dependency on mysql though.

**Comment by cressie176** [comment]
I've updated to use mysql2 (peer dependency), and updated the automated tests to run against mysql5 and mysql8. Published as marv-mysql-driver@4.0.0

**Comment by cressie176** [comment]
I think I'm going to rework slightly to not require either [mysql](https://www.npmjs.com/package/mysql) or [mysql2](https://www.npmjs.com/package/mysql2), and optionally require whichever is installed.

**Comment by cressie176** [comment]
Reworked and published as marv-mysql-driver@4.0.1
